version: '3'

volumes:
  try_rdbms_rb_gem_volume:
    driver: 'local'

services:
  rdbms_rb:
    build: ./rdbms/
    volumes:
      - ./rdbms/src:/myapp
      - ./rdbms/scripts:/var/scripts
      - try_rdbms_rb_gem_volume:/usr/local/bundle
    container_name: "rdbms_rb"
    command: /var/scripts/entry_point.sh
